name: CI

env:
  RUNNER_TOOL_CACHE: /toolcache

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master, develop]

jobs:
  install-cache:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout Commit
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 10
          run_install: false

      - name: Get info about cache
        id: get-pnpm-store-path
        run: |
          echo "PNPM_STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        id: cache-dependencies
        name: Setup pnpm cache
        with:
          path: ${{ steps.get-pnpm-store-path.outputs.PNPM_STORE_PATH  }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm

      - name: Install Dependencies
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: pnpm install --frozen-lockfile

      - name: Build project
        run: pnpm run build
