name: Common CI Steps

on:
  workflow_call:
    inputs:
      node-version:
        description: Node.js version
        required: true
        type: string
      run-audit:
        description: Whether to run the audit step
        required: false
        type: boolean
        default: false
      run-lint:
        description: Whether to run the eslint step
        required: false
        type: boolean
        default: false
      run-build:
        description: Whether to run the build step
        required: false
        type: boolean
        default: false
      run-sbom:
        description: Whether to run generation and upload SBOM artifacts step
        required: false
        type: boolean
        default: false

jobs:
  common:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.2.0
          run_install: false

      - name: Install Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
          cache: pnpm
          cache-dependency-path: '**/pnpm-lock.yaml'

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile --prefer-offline

      - name: Security Audit
        run: pnpm audit --prod
        if: ${{ inputs.run-audit }}

      - name: Lint
        run: npm run eslint
        if: ${{ inputs.run-lint }}

      - name: Build project
        run: npm run build
        if: ${{ inputs.run-build }}
        env:
          NODE_ENV: production

      - name: Generate SBOM
        uses: anchore/sbom-action@v0
        if: ${{ inputs.run-sbom }}
        with:
          format: cyclonedx-json
          output-file: sbom.json

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        if: ${{ inputs.run-sbom }}
        with:
          name: build-artifacts
          path: |
            dist/
          retention-days: 7
