name: Release pipeline

on:
  workflow_dispatch:
  push:
    branches: [master, develop, feature/**, hotfix/**]
  pull_request:
    branches: [master, develop]

jobs:
  ci:
    name: Quality checks
    uses: ./.github/workflows/common.yml
    permissions:
      actions: read
      contents: write
    strategy:
      matrix:
        node-version: [20.x]
    with:
      node-version: ${{ matrix.node-version }}
      run-audit: true
      run-lint: true
      run-build: true

  release:
    name: Release on production
    uses: ./.github/workflows/common.yml
    concurrency:
      group: semantic-release
      cancel-in-progress: true
    needs: [ci]
    if: ${{ github.ref == 'refs/heads/master' }}
    permissions:
      contents: write
      issues: write
      pull-requests: write
      deployments: write
    with:
      node-version: 20.x
      run-build: true
      run-sbom: true
      run-release: true
    secrets:
      SECRET_NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      BOT_SECRET_GITHUB_TOKEN: ${{ secrets.BOT_SECRET_GITHUB_TOKEN }}
