name: Build project

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master, develop]

jobs:
  install-cache:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 10.2.0

      - name: Install Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm
          cache-dependency-path: '**/pnpm-lock.yaml'

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint
        run: pnpm run eslint

      - name: Build project
        run: pnpm run build
