name: Release pipeline

on:
  workflow_dispatch:
  push:
    branches: [feature/**, hotfix/**]
  pull_request:
    branches: [master, develop]

jobs:
  ci:
    name: CI (quality checks)
    runs-on: ubuntu-24.04
    permissions:
      actions: read
      contents: write
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Common steps (checkout, install)
        uses: ./.github/workflows/ci-common-steps.yml
        with:
          node-version: [20.x]
          run-build: false

      - name: Security Audit
        run: |
          pnpm audit --prod

      - name: Lint
        run: pnpm run eslint

      - name: Build project
        run: pnpm run build
        env:
          NODE_ENV: production

      - name: Generate SBOM
        uses: anchore/sbom-action@v0
        with:
          format: cyclonedx-json
          output-file: sbom.json

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            dist/
            sbom.json
          retention-days: 7

  release:
    name: Release to production
    needs: [ci]
    runs-on: ubuntu-24.04
    if: ${{ github.ref == 'refs/heads/master' }}
    environment: production
    permissions:
      contents: write
      issues: write
      pull-requests: write
      deployments: write

    steps:
      - name: Common steps (checkout, install and build)
        uses: ./.github/workflows/ci-common-steps.yml
        with:
          node-version: [20.x]
          run-build: true

      - name: Semantic release
        run: npm run semantic-release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_CONFIG_USERCONFIG: ./.npmrc
